# Generated by Django 6.0.2 on 2026-02-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Contact',
            field=models.BigIntegerField(),
        ),
    ]
