# Generated by Django 6.0.2 on 2026-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_cpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Qualification',
            field=models.CharField(max_length=50),
        ),
    ]
